package ie.turfclub.model.stableStaff;

// default package
// Generated 28-Apr-2015 14:57:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeChances generated by hbm2java
 */
@Entity
@Table(name = "te_changes_log", catalog = "trainers")
public class TeChangesLog implements java.io.Serializable {

	private Integer logId;
	private Integer logTrainerId;
	private String logDetail;
	private TeEmployees logEmployeeId;


	public TeChangesLog() {
	}


	
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return logId;
	}





	public void setLogId(Integer logId) {
		this.logId = logId;
	}





	@Column(name = "log_trainer_id", nullable = false)
	public Integer getLogTrainerId() {
		return logTrainerId;
	}





	public void setLogTrainerId(Integer logTrainerId) {
		this.logTrainerId = logTrainerId;
	}




	@Column(name = "log_detail", nullable = false)
	public String getLogDetail() {
		return logDetail;
	}





	public void setLogDetail(String logDetail) {
		this.logDetail = logDetail;
	}




	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "log_employee_id", nullable = false)
	public TeEmployees getLogEmployeeId() {
		return logEmployeeId;
	}





	public void setLogEmployeeId(TeEmployees logEmployeeId) {
		this.logEmployeeId = logEmployeeId;
	}


	
	
}
