package ie.turfclub.model.stableStaff;

// default package
// Generated 28-Apr-2015 14:57:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TeChances generated by hbm2java
 */
@Entity
@Table(name = "te_chances", catalog = "trainers")
public class TeChances implements java.io.Serializable {

	private Integer chancesChanceId;
	private TeEmployees teEmployees;
	private String chancesTrackName;
	private Date chancesDateOfPass;
	private String chancesPassNumber;

	public TeChances() {
	}

	public TeChances(TeEmployees teEmployees, String chancesTrackName,
			Date chancesDateOfPass, String chancesPassNumber) {
		this.teEmployees = teEmployees;
		this.chancesTrackName = chancesTrackName;
		this.chancesDateOfPass = chancesDateOfPass;
		this.chancesPassNumber = chancesPassNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "chances_chance_id", unique = true, nullable = false)
	public Integer getChancesChanceId() {
		return this.chancesChanceId;
	}

	public void setChancesChanceId(Integer chancesChanceId) {
		this.chancesChanceId = chancesChanceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chances_employee_id", nullable = false)
	public TeEmployees getTeEmployees() {
		return this.teEmployees;
	}

	public void setTeEmployees(TeEmployees teEmployees) {
		this.teEmployees = teEmployees;
	}

	@Column(name = "chances_track_name", nullable = false, length = 50)
	public String getChancesTrackName() {
		return this.chancesTrackName;
	}

	public void setChancesTrackName(String chancesTrackName) {
		this.chancesTrackName = chancesTrackName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "chances_date_of_pass", nullable = false, length = 10)
	public Date getChancesDateOfPass() {
		return this.chancesDateOfPass;
	}

	public void setChancesDateOfPass(Date chancesDateOfPass) {
		this.chancesDateOfPass = chancesDateOfPass;
	}

	@Column(name = "chances_pass_number", nullable = false, length = 15)
	public String getChancesPassNumber() {
		return this.chancesPassNumber;
	}

	public void setChancesPassNumber(String chancesPassNumber) {
		this.chancesPassNumber = chancesPassNumber;
	}

}
