package ie.turfclub.model.stableStaff;
// Generated 28-Apr-2015 14:57:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TePension generated by hbm2java
 */
@Entity
@Table(name = "te_pension", catalog = "trainers")
public class TePension implements java.io.Serializable {

	private Integer pensionPensionId;
	private TeEmployees teEmployees;
	private Date pensionDateJoinedScheme;
	private Date pensionDateLeftScheme;

	public TePension() {
	}

	public TePension(TeEmployees teEmployees, Date pensionDateJoinedScheme) {
		this.teEmployees = teEmployees;
		this.pensionDateJoinedScheme = pensionDateJoinedScheme;
	}

	public TePension(TeEmployees teEmployees, Date pensionDateJoinedScheme,
			Date pensionDateLeftScheme) {
		this.teEmployees = teEmployees;
		this.pensionDateJoinedScheme = pensionDateJoinedScheme;
		this.pensionDateLeftScheme = pensionDateLeftScheme;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pension_pension_id", unique = true, nullable = false)
	public Integer getPensionPensionId() {
		return this.pensionPensionId;
	}

	public void setPensionPensionId(Integer pensionPensionId) {
		this.pensionPensionId = pensionPensionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pension_employee_id", nullable = false)
	public TeEmployees getTeEmployees() {
		return this.teEmployees;
	}

	public void setTeEmployees(TeEmployees teEmployees) {
		this.teEmployees = teEmployees;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pension_date_joined_scheme", nullable = false, length = 10)
	public Date getPensionDateJoinedScheme() {
		return this.pensionDateJoinedScheme;
	}

	public void setPensionDateJoinedScheme(Date pensionDateJoinedScheme) {
		this.pensionDateJoinedScheme = pensionDateJoinedScheme;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pension_date_left_scheme", length = 10)
	public Date getPensionDateLeftScheme() {
		return this.pensionDateLeftScheme;
	}

	public void setPensionDateLeftScheme(Date pensionDateLeftScheme) {
		this.pensionDateLeftScheme = pensionDateLeftScheme;
	}

}
