package ie.turfclub.model.stableStaff;
// Generated 28-Apr-2015 14:57:35 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.google.gson.annotations.Expose;

/**
 * TePension generated by hbm2java
 */
@Entity
@Table(name = "te_pension_approved", catalog = "trainers")
public class TePensionApproved implements java.io.Serializable {

	private Integer pensionPensionId;
	private TeEmployeesApproved teEmployees;
	private Date pensionDateJoinedScheme;
	private Date pensionDateLeftScheme;
	private String pensionCardType;
	private String pensionType;
	private TeTrainers pensionTrainer;
	private String pensionHRIAccNum;
	private String pensionTrainerName;
	private String pensionDateRange;
	@Expose
	private String employmentCategory;
	
	public TePensionApproved() {
	}

	public TePensionApproved(TeEmployeesApproved teEmployees, Date pensionDateJoinedScheme) {
		this.teEmployees = teEmployees;
		this.pensionDateJoinedScheme = pensionDateJoinedScheme;
	}

	public TePensionApproved(TeEmployeesApproved teEmployees, Date pensionDateJoinedScheme,
			Date pensionDateLeftScheme) {
		this.teEmployees = teEmployees;
		this.pensionDateJoinedScheme = pensionDateJoinedScheme;
		this.pensionDateLeftScheme = pensionDateLeftScheme;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pension_pension_id", unique = true, nullable = false)
	public Integer getPensionPensionId() {
		return this.pensionPensionId;
	}

	public void setPensionPensionId(Integer pensionPensionId) {
		this.pensionPensionId = pensionPensionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pension_employee_id", nullable = false)
	public TeEmployeesApproved getTeEmployees() {
		return this.teEmployees;
	}

	public void setTeEmployees(TeEmployeesApproved teEmployees) {
		this.teEmployees = teEmployees;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pension_date_joined_scheme", nullable = false, length = 10)
	public Date getPensionDateJoinedScheme() {
		return this.pensionDateJoinedScheme;
	}

	public void setPensionDateJoinedScheme(Date pensionDateJoinedScheme) {
		this.pensionDateJoinedScheme = pensionDateJoinedScheme;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pension_date_left_scheme", length = 10)
	public Date getPensionDateLeftScheme() {
		return this.pensionDateLeftScheme;
	}

	public void setPensionDateLeftScheme(Date pensionDateLeftScheme) {
		this.pensionDateLeftScheme = pensionDateLeftScheme;
	}
	
	@Column(name = "pension_card_type", length = 1)
	public String getPensionCardType() {
		return pensionCardType;
	}

	public void setPensionCardType(String pensionCardType) {
		this.pensionCardType = pensionCardType;
	}

	@Column(name = "pension_type", length = 1)
	public String getPensionType() {
		return pensionType;
	}

	public void setPensionType(String pensionType) {
		this.pensionType = pensionType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="pension_trainer")
	public TeTrainers getPensionTrainer() {
		return pensionTrainer;
	}

	public void setPensionTrainer(TeTrainers pensionTrainer) {
		this.pensionTrainer = pensionTrainer;
	}

	@Column(name = "pension_hri_acc_number", length = 30)
	public String getPensionHRIAccNum() {
		return pensionHRIAccNum;
	}

	public void setPensionHRIAccNum(String pensionHRIAccNum) {
		this.pensionHRIAccNum = pensionHRIAccNum;
	}

	@Transient
	public String getPensionTrainerName() {
		return pensionTrainerName;
	}

	public void setPensionTrainerName(String pensionTrainerName) {
		this.pensionTrainerName = pensionTrainerName;
	}

	@Transient
	public String getPensionDateRange() {
		return pensionDateRange;
	}

	public void setPensionDateRange(String pensionDateRange) {
		this.pensionDateRange = pensionDateRange;
	}

	@Column(name = "employment_category")
	public String getEmploymentCategory() {
		return employmentCategory;
	}

	public void setEmploymentCategory(String employmentCategory) {
		this.employmentCategory = employmentCategory;
	}
}
